format_version: 10
pipelines:
  Clientside:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0de2f4f:
        git: https://github.com/pranavparaswar/taskmanager1
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - pipeline2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Install-Dependencies:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - client
                command: cd
                run_if: passed
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
